<?php

namespace ContainerDcFK4zk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Nwia602Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.nwia602' shared service.
     *
     * @return \App\Controller\User
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\QuizzController::userhistory()": the $user argument is type-hinted with the non-existent class or interface: "App\\Controller\\User". Did you forget to add a use statement?');
    }
}
