<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjKnUup\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjKnUup/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUjKnUup.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUjKnUup\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUjKnUup\App_KernelDevDebugContainer([
    'container.build_hash' => 'UjKnUup',
    'container.build_id' => 'b6ff9dd4',
    'container.build_time' => 1621285268,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjKnUup');
